language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

services: redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
